### ISSUE TITLE
No Invocation Tracked

### ISSUE THREAD

**Issue by heberda** [stevenlauwers22/Glimpse.SignalR#3]
Using SignalR v 2.2.0 and Glimpse 1.8.6

Glimpse is picking up my Hub instance

But no invocations are being recorded.

_I appreciate support seems to have ground to a halt for this package, I thought it was still relevant to raise the issue._

**Comment by stevenlauwers22** [comment]
It's definitely still relevant to raise any problems with this package! :)
I'm not really actively working on this package, but if for some reason it breaks with a new version of glimpse or signalR, I'll try to get it workin again.

I'll probably have some time over the weekend.

**Comment by stevenlauwers22** [comment]
Invocations are being picked up, but the SignalR invocations tab does not get refreshed when new data is available. To be able to see the invocations you'll need to refresh your page.

I'm trying to find out how I can refactor the invocations tab so it picks up any new invocations without having to refresh the page.

I posted my question on the [Glimpse developer group](https://groups.google.com/forum/?fromgroups#!topic/getglimpse-dev/xFGn0YBh8uo).

**Comment by heberda** [comment]
Ok, awesome, I'll give it another shot, see if I can see some results :)

Thanks for looking into it so quickly!

**Comment by stevenlauwers22** [comment]
Work in progress, branch [feature-client-tab](https://github.com/stevenlauwers22/Glimpse.SignalR/tree/feature-client-tab)

**Comment by stevenlauwers22** [comment]
Done, a new version (v 1.1.0) has been released to NuGet.
The SignalR - Invocations tab now is a client tab (it polls every second for new invocations).
The tab shows up next to the Ajax/History tabs.
